import assert from 'node:assert/strict';
import fs from 'node:fs';
import {mean,median,ols,madScores,anomalies,changePointCUSUM,bootstrapSlopeCI,summarize} from './analytics.js';
const d=JSON.parse(fs.readFileSync('./data/budapest_nasa_power_2000_2024.json','utf8'));
assert.equal(d.rows.length,25);
assert.equal(mean([1,2,3]),2); assert.equal(median([3,1,2]),2);
let r=ols([1,2,3],[2,4,6]); assert.ok(Math.abs(r.slope-2)<1e-12); assert.ok(r.r2>.999999);
const zs=madScores([1,1,1,1,10]); assert.ok(zs[4]>2.5); assert.equal(anomalies([1,1,1,1,10]).length,1);
const cp=changePointCUSUM([0,0,0,0,10,10,10,10]); assert.ok(cp.index>=2&&cp.index<=5);
const ci=bootstrapSlopeCI([1,2,3,4,5],[1,2,3,4,5],400,42); assert.ok(ci.low>0&&ci.high>0);
const s=summarize(d.rows,'precip_mm'); assert.equal(s.years[0],2000); assert.equal(s.years.at(-1),2024); assert.ok(Number.isFinite(s.trend.slope)); assert.ok(s.ci.low<=s.ci.high); assert.ok(s.changePoint.index>0);
console.log('PASS EcoDrift analytics tests: 10 assertions / source rows:',d.rows.length);
